apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-crossplane-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other apps
spec:
  project: default
  source:
    repoURL: https://github.com/Kenbark42/argocd-crossplane-demo.git
    targetRevision: HEAD
    path: .
    directory:
      include: "argocd-crossplane-config.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true