apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy claims after infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/Kenbark42/argocd-crossplane-demo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: demo.io
    kind: CloudRunApp
    jsonPointers:
    - /status
    - /metadata/finalizers
    - /metadata/generation
    - /metadata/resourceVersion
    - /metadata/uid
    - /metadata/managedFields
    - /spec/resourceRef
    - /spec/compositionRevisionRef
    - /spec/compositionUpdatePolicy
    - /spec/writeConnectionSecretToRef
  - group: demo.io  
    kind: PostgreSQL
    jsonPointers:
    - /status
    - /metadata/finalizers
    - /metadata/generation
    - /metadata/resourceVersion
    - /metadata/uid
    - /metadata/managedFields
    - /spec/resourceRef
    - /spec/compositionRevisionRef
    - /spec/compositionUpdatePolicy
    - /spec/writeConnectionSecretToRef
