apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kenbark42/argocd-crossplane-demo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: demo.io
    kind: CloudRunApp
    jqPathExpressions:
    - .status
    - .metadata.finalizers
    - .metadata.generation
    - .metadata.resourceVersion
    - .metadata.uid
    - .metadata.managedFields
    - .spec.resourceRef
    - .spec.compositionRevisionRef
    - .spec.writeConnectionSecretToRef
  - group: demo.io  
    kind: PostgreSQL
    jqPathExpressions:
    - .status
    - .metadata.finalizers
    - .metadata.generation
    - .metadata.resourceVersion
    - .metadata.uid
    - .metadata.managedFields
    - .spec.resourceRef
    - .spec.compositionRevisionRef
    - .spec.writeConnectionSecretToRef
