apiVersion: demo.io/v1alpha1
kind: CloudRunApp
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
spec:
  parameters:
    region: us-central1
    image: gcr.io/darkfoo42/demo-app:v1.0.0
    databaseUrl: "postgresql://demo-user:demo-password@34.66.46.85:5432/demo-database"
  compositionRef:
    name: cloud-run-app
  writeConnectionSecretsToRef:
    name: cloudrun-connection
    namespace: demo
