apiVersion: demo.io/v1alpha1
kind: CloudRunApp
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
spec:
  parameters:
    region: us-central1
    image: gcr.io/darkfoo42/demo-app:v5.1.0
    dbSecretName: postgres-connection
  compositionRef:
    name: cloud-run-app
  writeConnectionSecretsToRef:
    name: cloudrun-connection
    namespace: demo
