apiVersion: demo.io/v1alpha1
kind: CloudRunApp
metadata:
  name: demo-app
  namespace: demo
spec:
  parameters:
    region: us-central1
    image: gcr.io/darkfoo42/demo-app:v1.0.0
    databaseUrl: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):5432/demo-database"
  compositionRef:
    name: cloud-run-app
  writeConnectionSecretsToRef:
    name: cloudrun-connection
    namespace: demo
