apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudrun
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-cloudrun:v1.12.0
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cloud-run-app
  labels:
    provider: gcp
    service: cloudrun
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: demo.io/v1alpha1
    kind: XCloudRunApp
  resources:
  - name: cloud-run-service
    base:
      apiVersion: cloudrun.gcp.upbound.io/v1beta1
      kind: Service
      spec:
        forProvider:
          location: us-central1
          template:
          - spec:
            - containers:
              - image: gcr.io/cloudrun/hello
                ports:
                - containerPort: 8080
                env:
                - name: GOOGLE_CLOUD_PROJECT
                  value: darkfoo42
                - name: NODE_ENV
                  value: production
                resources:
                - limits:
                    cpu: "1000m"
                    memory: "512Mi"
          traffic:
          - percent: 100
            latestRevision: true
        writeConnectionSecretsToRef:
          namespace: crossplane-system
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
    - fromFieldPath: spec.parameters.image
      toFieldPath: spec.forProvider.template[0].spec[0].containers[0].image
    connectionDetails:
    - fromConnectionSecretKey: url
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcloudrnapps.demo.io
spec:
  group: demo.io
  names:
    kind: XCloudRunApp
    plural: xcloudrnapps
  claimNames:
    kind: CloudRunApp
    plural: cloudrunapps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    default: us-central1
                  image:
                    type: string
                    default: gcr.io/cloudrun/hello
                  dbSecretName:
                    type: string
                    default: postgres-connection
                required:
                - region
                - image
            required:
            - parameters
          status:
            type: object
            properties:
              ready:
                type: boolean