apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: Service
metadata:
  name: demo-app-with-secrets
spec:
  forProvider:
    location: us-central1
    template:
    - spec:
      - containers:
        - image: gcr.io/darkfoo42/demo-app:v1.0.0
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: latest
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
    traffic:
    - latestRevision: true
      percent: 100
  providerConfigRef:
    name: default