---
apiVersion: v1
kind: Secret
metadata:
  name: database-connection-data
  namespace: crossplane-system
stringData:
  host: "34.66.46.85"
  port: "5432"
  database: "demo-database"
  username: "demo-user"
  password: "demo-password"
  connectionString: "postgresql://demo-user:demo-password@34.66.46.85:5432/demo-database"
---
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: database-credentials
spec:
  forProvider:
    secretId: database-credentials
    labels:
      app: demo-postgres
      managed-by: crossplane
    replication:
    - auto: {}
  providerConfigRef:
    name: secretmanager-config
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: database-credentials-version
spec:
  forProvider:
    secretSelector:
      matchLabels:
        app: demo-postgres
    secretDataSecretRef:
      name: database-connection-data
      namespace: crossplane-system
      key: connectionString
  providerConfigRef:
    name: secretmanager-config