apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: database-credentials
spec:
  forProvider:
    labels:
      app: demo-postgres
      managed-by: crossplane
    replication:
    - automatic: true
  providerConfigRef:
    name: secretmanager-config