apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cloudrun-with-secrets
  labels:
    provider: gcp
    service: cloudrun
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: demo.io/v1alpha1
    kind: XCloudRunApp
  resources:
  - name: cloud-run-service
    base:
      apiVersion: cloudrun.gcp.upbound.io/v1beta1
      kind: Service
      spec:
        forProvider:
          location: us-central1
          template:
          - spec:
            - containers:
              - image: gcr.io/cloudrun/hello
                env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: database-secret
                      key: latest
        writeConnectionSecretsToRef:
          namespace: crossplane-system
        providerConfigRef:
          name: default
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
    - fromFieldPath: spec.parameters.image
      toFieldPath: spec.forProvider.template[0].spec[0].containers[0].image
    - fromFieldPath: spec.parameters.secretName
      toFieldPath: spec.forProvider.template[0].spec[0].containers[0].env[0].valueFrom.secretKeyRef.name
    connectionDetails:
    - fromConnectionSecretKey: url