apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: postgres-credentials
spec:
  forProvider:
    secretId: postgres-credentials
    labels:
      app: demo-postgres
      managed-by: crossplane
    replication:
      automatic: true
  providerConfigRef:
    name: secretmanager-config