apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgres-db
  labels:
    provider: gcp
    service: cloudsql
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: demo.io/v1alpha1
    kind: XPostgreSQL
  resources:
  - name: cloudsql-instance
    base:
      apiVersion: database.gcp.crossplane.io/v1beta1
      kind: CloudSQLInstance
      spec:
        forProvider:
          databaseVersion: POSTGRES_13
          region: us-central1
          settings:
            tier: db-f1-micro
            availabilityType: ZONAL
            dataDiskSizeGb: 20
            dataDiskType: PD_SSD
            backupConfiguration:
              enabled: true
              pointInTimeRecoveryEnabled: true
            ipConfiguration:
              authorizedNetworks:
                - value: "0.0.0.0/0"
              ipv4Enabled: true
        writeConnectionSecretsToRef:
          namespace: crossplane-system
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
    - fromFieldPath: spec.parameters.size
      toFieldPath: spec.forProvider.settings.tier
      transforms:
      - type: map
        map:
          small: db-f1-micro
          medium: db-n1-standard-1
          large: db-n1-standard-2
    connectionDetails:
    - name: host
      fromFieldPath: status.atProvider.ipAddresses[0].ipAddress
    - name: port
      value: "5432"
    - name: database
      value: "demo-database"
    - name: username
      value: "demo-user"
    - name: password
      value: "demo-password"
    - name: connectionName
      fromFieldPath: status.atProvider.connectionName