apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-secretmanager
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-secretmanager:v1.14.1
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: secretmanager-config
spec:
  projectID: darkfoo42
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-secret
      key: creds